### ISSUE TITLE
Cannot load model checkpoint

### ISSUE THREAD

**Issue by payalchandak** [payalchandak/EveryQuery#4]
weird error after reaching inference
```
Traceback (most recent call last):                                                
  File "/storage2/payal/EveryQuery/meds-torch/src/meds_torch/utils/utils.py", line
 67, in wrap                                                                      
    outputs = task_func(cfg=cfg, **kwargs)                                        
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                        
  File "/storage2/payal/EveryQuery/src/train.py", line 109, in train              
    trainer.test(model=model, datamodule=datamodule, ckpt_path=best_model_path)   
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/lightning/py
torch/trainer/trainer.py", line 748, in test                                      
    return call._call_and_handle_interrupt(                                       
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                       
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/lightning/py
torch/trainer/call.py", line 47, in _call_and_handle_interrupt                    
    return trainer_fn(*args, **kwargs)                                            
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                            
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/lightning/py
torch/trainer/trainer.py", line 788, in _test_impl                                
    results = self._run(model, ckpt_path=ckpt_path)                               
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                               
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/lightning/py
torch/trainer/trainer.py", line 950, in _run                                      
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)          
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/lightning/py
torch/trainer/connectors/checkpoint_connector.py", line 397, in _restore_modules_a
nd_callbacks        
    self.resume_start(checkpoint_path)
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/lightning/py
torch/trainer/connectors/checkpoint_connector.py", line 79, in resume_start       
    loaded_checkpoint = self.trainer.strategy.load_checkpoint(checkpoint_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/lightning/py
torch/strategies/strategy.py", line 367, in load_checkpoint                       
    return self.checkpoint_io.load_checkpoint(checkpoint_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/lightning/fa
bric/plugins/io/torch_io.py", line 83, in load_checkpoint                         
    return pl_load(path, map_location=map_location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/lightning/fa
bric/utilities/cloud_io.py", line 60, in _load                                    
    return torch.load(                                                            
           ^^^^^^^^^^^
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/torch/serial
ization.py", line 1097, in load                                                 
    return _load(                       
           ^^^^^^                                                               
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/torch/serial
ization.py", line 1525, in _load                                                
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^                                                   
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/pickle.py", line 1205, in 
load                
    dispatch[key[0]](self)
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/pickle.py", line 1710, in 
load_build          
    setstate(state)
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/polars/serie
s/series.py", line 646, in __setstate__  
    self._s.__setstate__(state)
polars.exceptions.ComputeError: out-of-spec: ExpectedBuffer
```

it seems to be something with how the checkpoint is saved
```
>>> ckpt = torch.load('/storage2/payal/EveryQuery/results/2024-11-16_23-59-13_272579/checkpoints/epoch_006.ckpt')
<stdin>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/torch/serialization.py", line 1097, in load
    return _load(
           ^^^^^^
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/torch/serialization.py", line 1525, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "/home/chandak/miniconda3/envs/eq/lib/python3.12/site-packages/polars/series/series.py", line 646, in __setstate__
    self._s.__setstate__(state)
polars.exceptions.ComputeError: out-of-spec: ExpectedBuffer
```

I cannot load the checkpoint with pickle
```
with open('/storage2/payal/EveryQuery/results/2024-11-16_23-59-13_272579/checkpoints/epoch_006.ckpt', 'rb') as f:
...     data = pickle.load(f)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.

```

**Comment by mmcdermott** [comment]
Possibilities:
1. Nassim has a resolver which loads a polars dataframe from a parquet file here: https://github.com/Oufattole/meds-torch/blob/3f1b835abfb550cf4d2491c6f764a5f1a96650d9/src/meds_torch/utils/resolvers.py#L12
This could be somehow caching the dataframe somehow, requiring the whole polars object to be re-loaded upon torch.load.
2. Your dataset class, which is [instantiated via the OmegaConf `_target_` parameter](https://github.com/payalchandak/EveryQuery/blob/ed5a70de5d6054d1502d7181291fb0c6b0647f3b/src/configs/data/dataset/everyquery_dataset.yaml),, [has as a member variable a polars dataframe](https://github.com/payalchandak/EveryQuery/blob/ed5a70de5d6054d1502d7181291fb0c6b0647f3b/src/dataset.py#L32). During saving, the config may already be initialized which would convert this member to an object. **_This is very likely the actual cause._**
3. You could change the `pickle_module` used during saving / loading from pickle to dill, which may deal better with storing dataframes. I'm not sure if this is possible through Lightning, though it is in raw torch. You'd need to do this during both saving and loading. This is likely a worse solution than just making your dataset class store plain old data.

**Comment by payalchandak** [comment]
Resolved by storing `metadata` and `code_options` as dictionaries instead of polars data frames. It's okay to store polars schema objects. Ensure you convert to dict using to_dicts and not to_dict (or anything else which stores polars series)
